[containers]
init = true
init_path = "/var/lib/platformd/releases/current/runtime/catatonit"
log_driver = "k8s-file"
seccomp_profile = "/var/lib/platformd/releases/current/runtime/seccomp.json"

[engine]
cgroup_manager = "cgroupfs"
conmon_path = ["/var/lib/platformd/releases/current/runtime/conmon"]
db_backend = "sqlite"
events_logger = "file"
helper_binaries_dir = ["/var/lib/platformd/releases/current/runtime"]
hooks_dir = ["/run/platformd/containers/hooks"]
image_volume_mode = "ignore"
network_backend = "netavark"
runtime = "/var/lib/platformd/releases/current/runtime/crun"

[network]
network_backend = "netavark"
