[package]
name = "platformd-objectstore"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"

[workspace]

[dependencies]
async-trait = "=0.1.91"
base64 = "=0.22.1"
bytes = "=1.12.1"
futures-util = "=0.3.33"
http = "=1.5.0"
http-body-util = "=0.1.4"
hyper = { version = "=1.11.0", features = ["http1", "server"] }
hyper-util = { version = "=0.1.20", features = ["tokio"] }
rustfs-ecstore = { git = "https://github.com/rustfs/rustfs.git", rev = "2e5cef513fb31e25940f1c77e208f28b302561bb", default-features = false }
rustfs-heal = { git = "https://github.com/rustfs/rustfs.git", rev = "2e5cef513fb31e25940f1c77e208f28b302561bb" }
rustfs-rio = { git = "https://github.com/rustfs/rustfs.git", rev = "2e5cef513fb31e25940f1c77e208f28b302561bb" }
rustfs-storage-api = { git = "https://github.com/rustfs/rustfs.git", rev = "2e5cef513fb31e25940f1c77e208f28b302561bb" }
s3s = { git = "https://github.com/cxymds/s3s.git", rev = "fe3941d91fa1c69956f209a9145995c9f0235bff", features = ["minio"] }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
time = "=0.3.54"
tokio = { version = "=1.53.1", features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "signal"] }
tokio-util = { version = "=0.7.19", features = ["io", "rt"] }

[dev-dependencies]
tempfile = "=3.27.0"

[profile.release]
panic = "abort"
strip = "symbols"
